### ISSUE TITLE
What's happening on date intent.

### ISSUE THREAD

**Issue by jorgecanchola** [370-Alexa-Project/CS370_Echo_Demo#33] opened 2016-10-18 21:58 UTC
**Name:** EventsOnDateIntent

**Description:** The user just asked about a specific date and Alexa just gave you the date. We need to check to see how many events there are on that day, and then have Alexa either list off the events (if there are less than 13), or say that there are X number of events and then ask the user which category they want to hear about. If there are not any events on the given date, we can just say that we couldn't find any events.

**Example Interactions:**
Case 0 - If there are no events on the given day:
User: "What is happening on Tuesday?"
Alexa: "Sorry, I could not find anything happening on Tuesday."

Case 1 - If there are less than 13 events:
User: "What is happening on Tuesday?"
Alexa: <List off all of the events and their times>

Case 2 - If there are more than 13 events on the given day:
User: "What is happening on Tuesday?"
Alexa:  On Tuesday there are 15 events. Would you like to hear all of them, or about <list off calendars types> ? 

User: "All of them"
Alexa : <reads list of all events happening on the day the user asked about>
or
User: "Sports"
Alexa: <reads list of events for only the sports category>

**Preconditions:** None

**Postcondition:** 
Store the number of events on the date in numEventsOnDate. 
StateID = 1000 if there is  less than 13 events. 
StateID = 1001 if there is more than or equal to 13 events. 
Store the date the user asks for in latestDate. 
eventNames has the names of all of the events that Alexa previously said.

**Comment by ghost** [comment] 2016-10-25 00:08
Duplicate of #24

**Closed as completed by ghost** 2016-10-25 00:08 UTC
Labels: duplicate, feature, alexa skill
